version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - kolasokol
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - kolasokol
